routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['user']], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');

    // categories
    Route::resource('categories', 'CategoryController');
    Route::prefix('categories')->group(function (){
        Route::get('/delete-or-restore/{category}', 'CategoryController@deleteOrRestore')->name('categories.delete');
    });

    // products
    Route::resource('products', 'ProductController');
    Route::prefix('products')->group(function (){
        Route::get('/delete-or-restore/{product}', 'ProductController@deleteOrRestore')->name('products.delete');
    });

    // purchases
    Route::resource('purchases', 'PurchaseController');
    Route::prefix('purchases')->group(function (){
        Route::get('/delete-or-restore/{purchase}', 'PurchaseController@deleteOrRestore')->name('purchases.delete');
        Route::get('/product-form/{index?}', 'PurchaseController@productForm')->name('purchases.productForm');
    });

    // sales
    Route::resource('sales', 'SaleController');
    Route::prefix('sales')->group(function (){
        Route::get('/delete-or-restore/{sale}', 'SaleController@deleteOrRestore')->name('sales.delete');
        Route::get('/product-form/{index?}', 'SaleController@productForm')->name('sales.productForm');
    });

    // suppliers
    Route::resource('suppliers', 'SupplierController');
    Route::prefix('suppliers')->group(function (){
        Route::get('/delete-or-restore/{supplier}', 'SupplierController@deleteOrRestore')->name('suppliers.delete');
    });

    // customers
    Route::resource('customers', 'CustomerController');
    Route::prefix('customers')->group(function (){
        Route::get('/delete-or-restore/{customer}', 'CustomerController@deleteOrRestore')->name('customers.delete');
    });

    // users
    Route::resource('users', 'UserController');
    Route::prefix('users')->group(function (){
        Route::get('/delete-or-restore/{user}', 'UserController@deleteOrRestore')->name('users.delete');
    });

    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::match(['put', 'patch'], 'profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::match(['put', 'patch'], 'profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

    Route::resource('roles', 'RoleController');
    Route::prefix('roles')->group(function (){
    Route::get('/delete-or-restore/{role}', 'RoleController@deleteOrRestore')->name('roles.delete');
    });

    Route::resource('permissions', 'PermissionController');
    Route::prefix('permissions')->group(function (){
    Route::get('/delete-or-restore/{permission}', 'PermissionController@deleteOrRestore')->name('permissions.delete');
    });

});


Route::view('user/login', 'user.login')->name('user.login');
Route::post('user/do-login', 'UserController@doLogin')->name('user.doLogin');
Route::get('user/register', 'UserController@register')->name('user.register');
Route::post('user/do-register', 'UserController@doRegister')->name('user.doRegister');
Route::post('/logout', 'UserController@logout')->name('logout');

app/Models/Supplier.php
<?php

namespace App\Models;

use App\Utils\AppUtils;
use Carbon\Carbon;
use Exception;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Supplier extends Model{

    use SoftDeletes;

    protected $fillable = [
        'name', 'email', 'phone', 'image', 'address', 'created_by', 'updated_by'
    ];

    // ===================== ORM Definition START ===================== //

    /**
     * @return HasMany
     */
    public function products(){
        return $this->hasMany(Product::class);
    }

    /**
     * @return BelongsToMany
     */
    public function purchases(){
        return $this->hasMany(Purchase::class);
    }

    /**
     * @return BelongsTo
     */
    public function createdBy(){
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * @return BelongsTo
     */
    public function updatedBy(){
        return $this->belongsTo(User::class, 'updated_by');
    }

    // ===================== ORM Definition END ===================== //

    /**
     * get specified supplier by id
     * @param int $id
     * @param bool $withTrashed
     * @return array
     */
    public function getSupplierById(int $id, $withTrashed = false) {

        $supplier = $this->newQuery()
            ->where('id', $id)
            ->when($withTrashed, function ($query){
                $query->withTrashed();
            })
            ->firstOrFail()->format();

        $data = [];
        if ($supplier){
            $data['status'] = true;
            $data['supplier'] = $supplier;
        }else{
            $data['status'] = false;
            $data['supplier'] = [];
        }

        return $data;
    }

    /**
     * @param string $name
     * @param bool $withTrashed
     * @return mixed
     */
    public function getSupplierByName(string $name, $withTrashed = false) {
        $supplier = $this::where('name', $name)
            ->when($withTrashed, function ($query){
                $query->withTrashed();
            })
            ->with([
                'purchases'
            ])
            ->firstOrFail()->format();

        $data['status'] = true;
        $data['supplier'] = $supplier;

        return $data;
    }
    /**
     * @param bool $withTrashed
     * @return Collection
     */
    public function getSuppliers($withTrashed = false) {
        return $this->when($withTrashed, function ($query){
                $query->withTrashed();
            })
            ->get()->map(function ($supplier){
                return $supplier->format();
            });
    }
    /**
     * format supplier object
     * @return array
     */
    public function format(){
        return [
            'id' => $this->id,
            'created_by' => $this->createdBy->name,
            'updated_by' => $this->updateddBy ? $this->updateddBy->name : '-',
            'name' => $this->name,
            'email' => $this->email,
            'phone' => $this->phone,
            'image' => asset('storage/'.$this->image),
            'address' => $this->address,
            'created_at' => $this->created_at,
            'updated_at' => $this->created_at,
            'deleted_at' => $this->deleted_at,
        ];
    }

    /**
     * store new supplier
     * @param array $fields
     * @return array
     */
    public function storeSupplier(array $fields) {
        $supplierImage = $fields['image'];
        $supplierImage = AppUtils::base64ToImage($supplierImage);
        $imageName = time() . 'supplier.png';
        $fields['created_by'] = auth()->id();
        $fields['image'] = 'supplier/' . $imageName;
        $supplier = $this::create($fields);

        $data = [];
        if ($supplier) {
            $data['status'] = true;
            $data['message'] = "New Supplier was added";
            Storage::disk()->put('supplier/' . $imageName, $supplierImage);
        } else {
            $data['status'] = false;
            $data['message'] = "There is problem adding new supplier";
        }

        return $data;
    }

    /**
     * @param array $fields
     * @param int $id
     * @return mixed
     */
    public function updateSupplier(array $fields, int $id) {
        $supplier = $this::withTrashed()->findOrFail($id);
        if ($supplier){
            if ($fields['image']){
                $oldImage = $supplier->image;
                $supplierImage = $fields['image'];
                $supplierImage = AppUtils::base64ToImage($supplierImage);
                $imageName = time() . 'supplier.png';
                $fields['image'] = 'supplier/' . $imageName;
                Storage::disk()->put('supplier/' . $imageName, $supplierImage);
                unlink(storage_path('app/public/' . $oldImage));
            }else{
                unset($fields['image']);
            }

            $fields['updated_by'] = auth()->id();
            $supplier->update($fields);
            $data['status'] = true;
            $data['message'] = "Supplier was updated";
        }else{
            $data['status'] = false;
            $data['message'] = "There is problem updating supplier";
        }

        return $data;
    }

    /**
     * @param int $id
     * @return array
     */
    public function destroySupplier(int $id) {
        $supplier = $this::withTrashed()->where('id', $id)->firstOrFail();
        $data = [];
        if ($supplier){
            $oldImage = $supplier->image;
            $supplier->forceDelete();
            unlink(storage_path('app/public/' . $oldImage));
            $data['status'] = true;
            $data['message'] = "Supplier was deleted";
        }else{
            $data['status'] = false;
            $data['message'] = "There is problem deleting supplier";
        }

        return $data;
    }

    /**
     * @param $id
     * @return array
     */
    public function deleteOrRestore($id) {
        $data = [];
        $supplier = $this::withTrashed()->findOrFail($id);
        if ($supplier){
            if ($supplier->trashed()){
                $supplier->restore();
            }else{
                try {
                    $supplier->delete();
                } catch (Exception $e) {
                }
            }
            $data['status'] = true;
            $data['message'] = "Supplier status was updated";
        }else {
            $data['status'] = false;
            $data['message'] = "Supplier not found";
        }

        return $data;
    }

}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SupplierFormRequest;
use App\Models\Supplier;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class SupplierController extends Controller {

    /**
     * @var Supplier
     */
    private $supplier;

    /**
     * SupplierController constructor.
     * @param Supplier $supplier
     */
    public function __construct(Supplier $supplier) {
        $this->supplier = $supplier;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index() {
        $suppliers = $this->supplier->getSuppliers(true);
        return view('suppliers.index', compact('suppliers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create() {
        return view('suppliers.create');
    }

    /**
     * Store a newly created supplier in storage.
     *
     * @param SupplierFormRequest $request
     * @return Response
     */
    public function store(SupplierFormRequest $request) {
        $fields = $request->validated();
        $data = $this->supplier->storeSupplier($fields);
        return redirect()->route('suppliers.index')->with($data);
    }

    /**
     * Display the specified supplier.
     *
     * @param string $slug
     * @return Response
     */
    public function show($id) {
        $data = $this->supplier->getSupplierById($id);
        return view('suppliers.show', $data);
    }

    /**
     * Show the form for editing the specified supplier.
     *
     * @param int $id
     * @return Response
     */
    public function edit($id) {
        $data = $this->supplier->getSupplierById($id);
        return view('suppliers.edit', $data);
    }

    /**
     * Update the specified supplier in storage.
     *
     * @param SupplierFormRequest $request
     * @param int $id
     * @return Response
     */
    public function update(SupplierFormRequest $request, $id) {
        $fields = $request->validated();
        $data = $this->supplier->updateSupplier($fields, $id);
        return redirect()->route('suppliers.index')->with($data);
    }

    /**
     * Remove the specified supplier from storage.
     *
     * @param int $id
     * @return Response
     */
    public function destroy($id) {
        $data = $this->supplier->destroySupplier($id);
        return json_encode($data);
    }

    public function deleteOrRestore($id){
        $data = $this->supplier->deleteOrRestore($id);
        return json_encode($data);
    }
}

resources/views/suppliers/create.blade.php
@extends('layouts.master')

@section('title', 'Create Supplier')

@section('css')
    <link href="{{asset('assets/css/select2.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('assets/css/cropper.css')}}" rel="stylesheet" type="text/css">
    <style>
        span.select2-container{
            width: 100% !important;
        }
    </style>
@endsection

@section('content')
    @include('partials._crop-image-modal')

    <div class="page-heading">
        <h1 class="page-title">Create Supplier</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{route('dashboard')}}"><i class="fa fa-home font-20"></i></a>
            </li>
            <li class="breadcrumb-item">Create Supplier</li>
        </ol>
    </div>

    @include('suppliers.form')
@endsection

@section('js')
    <script src="{{asset('assets/js/select2.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/js/jquery.validate.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/js/cropper.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/js/image-cropper-modal.js')}}" type="text/javascript"></script>
    <script type="text/javascript">
        let rules = {
            name: {
                minlength: 2,
                required: !0
            },
            phone: {
                minlength: 8,
                required: !0
            },
            image: {
                minlength: 10
            },
        };
    </script>
    <script src="{{asset('assets/js/suppliers.js')}}" type="text/javascript"></script>
@endsection

resources/views/suppliers/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit Supplier')

@section('css')
    <link href="{{asset('assets/css/select2.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('assets/css/cropper.css')}}" rel="stylesheet" type="text/css">
    <style>
        span.select2-container{
            width: 100% !important;
        }
    </style>
@endsection

@section('content')
    @include('partials._crop-image-modal')

    <div class="page-heading">
        <h1 class="page-title">Edit Supplier</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{route('dashboard')}}"><i class="fa fa-home font-20"></i></a>
            </li>
            <li class="breadcrumb-item">Edit Supplier</li>
        </ol>
    </div>

    @include('suppliers.form')
@endsection

@section('js')
    <script src="{{asset('assets/js/select2.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/js/jquery.validate.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/js/cropper.js')}}" type="text/javascript"></script>
    <script src="{{asset('assets/js/image-cropper-modal.js')}}" type="text/javascript"></script>
    <script type="text/javascript">
        let rules = {
            name: {
                minlength: 2,
                required: !0
            },
            phone: {
                minlength: 8,
                required: !0
            },
            image: {
                minlength: 10
            },
        };
    </script>
    <script src="{{asset('assets/js/suppliers.js')}}" type="text/javascript"></script>
@endsection

resources/views/suppliers/form.blade.php
<div class="page-content">
    <div class="ibox">
        <div class="ibox-head">
            <div class="ibox-title">{{isset($supplier) ? 'Edit' : 'Create'}} Supplier</div>
        </div>
        <div class="ibox-body">
            <div class="row">
                <div class="col-md-8">
                    <form action="{{isset($supplier) ? route('suppliers.update', $supplier['id']) : route('suppliers.store')}}" method="post" novalidate="novalidate" id="supplierForm" enctype="multipart/form-data">
                        @csrf
                        @if(isset($supplier))
                            @method('PUT')
                        @endif
                        <div class="form-group required row">
                            <label for="supplier_name" class="col-sm-3 col-form-label">Supplier Name:</label>
                            <div class="col-sm-9">
                                <input class="form-control {{\App\Utils\AppUtils::inputFieldError($errors, 'supplier_name')}}" name="name" value="{{isset($supplier) ? $supplier['name'] : old('name')}}" id="name" type="text" placeholder="Supplier Name">
                                @include('partials._error', ['field' => 'name'])
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="supplier_email" class="col-sm-3 col-form-label">Supplier Email:</label>
                            <div class="col-sm-9">
                                <input class="form-control {{\App\Utils\AppUtils::inputFieldError($errors, 'email')}}" name="email" value="{{isset($supplier) ? $supplier['email'] : old('email')}}" id="email" type="text" placeholder="Supplier Email">
                                @include('partials._error', ['field' => 'email'])
                            </div>
                        </div>
                        <div class="form-group required row">
                            <label for="supplier_phone" class="col-sm-3 col-form-label">Supplier Phone:</label>
                            <div class="col-sm-9">
                                <input class="form-control {{\App\Utils\AppUtils::inputFieldError($errors, 'phone')}}" name="phone" value="{{isset($supplier) ? $supplier['phone'] : old('phone')}}" id="phone" type="number" placeholder="Supplier Phone">
                                @include('partials._error', ['field' => 'phone'])
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="supplier_address" class="col-sm-3 col-form-label">Supplier Address:</label>
                            <div class="col-sm-9">
                                <input class="form-control {{\App\Utils\AppUtils::inputFieldError($errors, 'address')}}" name="address" value="{{isset($supplier) ? $supplier['address'] : old('address')}}" id="address" type="text" placeholder="Supplier Address">
                                @include('partials._error', ['field' => 'address'])
                            </div>
                        </div>
                        <div class="form-group {{isset($supplier) ? '' : 'required'}} row">
                            <label for="supplier_image_picker" class="col-sm-3 col-form-label">Supplier Image:</label>
                            <div class="col-sm-9">
                                <input class="form-control {{\App\Utils\AppUtils::inputFieldError($errors, 'image')}}"  id="supplier_image_picker" type="file" accept=".png, .jpg">
                                <input type="text" style="position: absolute; z-index: -1" name="image" value="" id="image">
                                @include('partials._error', ['field' => 'image'])
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label"></label>
                            <div class="col-sm-9">
                                <button type="submit" class="btn btn-primary btn-block">{{isset($supplier) ? 'Update' : 'Create'}} Supplier</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-4">
                    <img src="{{isset($supplier) ? $supplier['image'] : asset('assets/img/image.png')}}" class="img-fluid" id="supplierImagePreview" alt="supplier">
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/suppliers/index.blade.php
@extends('layouts.master')

@section('title', 'Manage Suppliers')

@section('css')
    <link href="{{asset('assets/css/datatables.min.css')}}" rel="stylesheet" />
@endsection

@section('content')
    <div class="page-heading">
        <h1 class="page-title">Manage Suppliers</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{route('dashboard')}}"><i class="fa fa-home font-20"></i></a>
            </li>
            <li class="breadcrumb-item">Manage Suppliers</li>
        </ol>
    </div>
    <div class="page-content fade-in-up">
        <div class="ibox">
            <div class="ibox-head">
                <div class="ibox-title">Suppliers</div>
            </div>
            <div class="ibox-body">
                <table class="table table-striped table-bordered table-hover" id="supplier-table" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Images</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Address</th>
                        <th>Created At</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($suppliers as $supplier)
                        <tr data-index="{{$supplier['id']}}">
                            <td>{{$supplier['id']}}</td>
                            <td><img class="img-fluid img-50" alt="image" src="{{$supplier['image']}}"></td>
                            <td>{{$supplier['name']}}</td>
                            <td>{{$supplier['email']}}</td>
                            <td>{{$supplier['phone']}}</td>
                            <td>{{$supplier['address']}}</td>
                            <td>{{$supplier['created_at']}}</td>
                            <td class="text-center">
                                <a href="{{route('suppliers.show', $supplier['id'])}}" class="btn btn-info btn-xs m-r-5" data-toggle="tooltip" data-original-title="View"><i class="fa fa-eye font-14"></i></a>
                                <a href="{{route('suppliers.edit', $supplier['id'])}}" class="btn btn-primary btn-xs m-r-5" data-toggle="tooltip" data-original-title="Edit"><i class="fa fa-pencil font-14"></i></a>
                                <a href="{{route('suppliers.destroy', $supplier['id'])}}" class="btn btn-danger delete-supplier btn-xs m-r-5" data-toggle="tooltip" data-original-title="Delete"><i class="fa fa-trash font-14"></i></a>
                                <div class="switch_box">
                                    <div class="input_wrapper">
                                        <input type="checkbox" data-url="{{route('suppliers.delete', $supplier['id'])}}" {{$supplier['deleted_at'] == null ? 'checked' : ''}} class="switch_4 soft-delete-supplier">
                                        <svg class="is_checked" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 426.67 426.67">
                                            <path d="M153.504 366.84c-8.657 0-17.323-3.303-23.927-9.912L9.914 237.265c-13.218-13.218-13.218-34.645 0-47.863 13.218-13.218 34.645-13.218 47.863 0l95.727 95.727 215.39-215.387c13.218-13.214 34.65-13.218 47.86 0 13.22 13.218 13.22 34.65 0 47.863L177.435 356.928c-6.61 6.605-15.27 9.91-23.932 9.91z"/>
                                        </svg>
                                        <svg class="is_unchecked" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 212.982 212.982">
                                            <path d="M131.804 106.49l75.936-75.935c6.99-6.99 6.99-18.323 0-25.312-6.99-6.99-18.322-6.99-25.312 0L106.49 81.18 30.555 5.242c-6.99-6.99-18.322-6.99-25.312 0-6.99 6.99-6.99 18.323 0 25.312L81.18 106.49 5.24 182.427c-6.99 6.99-6.99 18.323 0 25.312 6.99 6.99 18.322 6.99 25.312 0L106.49 131.8l75.938 75.937c6.99 6.99 18.322 6.99 25.312 0 6.99-6.99 6.99-18.323 0-25.313l-75.936-75.936z" fill-rule="evenodd" clip-rule="evenodd"/>
                                        </svg>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script src="{{asset('assets/js/datatables.min.js')}}" type="text/javascript"></script>
    <script type="text/javascript">
        let dataTable = $('#supplier-table').DataTable({
            pageLength: 10,
            responsive: true
        });

        $(document).on('change', '.soft-delete-supplier', function (e) {
            let url = $(this).attr('data-url');

            $.get(url, function (response) {
                if (JSON.parse(response).status){
                    showToast('Success', JSON.parse(response).message, 'success');
                }else {
                    showToast('Error', JSON.parse(response).message, 'error');
                }
            })
        });

        $(document).on('click', '.delete-supplier', function (e) {
            e.preventDefault();
            let isDelete = confirm('Do you really want to permanently delete?');
            if (isDelete){
                let row = $(this).parents('tr');
                let url = $(this).attr('href');
                $.ajax({
                    url: url,
                    type: 'DELETE',
                    success: function (response) {
                        if (JSON.parse(response).status){
                            showToast('Success', JSON.parse(response).message, 'success');
                            dataTable.row(row).remove().draw(false);
                        } else {
                            showToast('Error', JSON.parse(response).message, 'error');
                        }
                    }
                });
            }
        });
    </script>
@endsection

resources/views/suppliers/show.blade.php
@extends('layouts.master')

@section('title', $supplier['name'])

@section('content')
    <div class="page-heading">
        <h1 class="page-title">Supplier Detail</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{route('dashboard')}}"><i class="fa fa-home font-20"></i></a>
            </li>
            <li class="breadcrumb-item">Supplier Detail</li>
        </ol>
    </div>

    <div class="page-content fade-in-up">
        <div class="ibox">
            <div class="ibox-head">
                <div class="ibox-title">Supplier</div>
            </div>
            <div class="ibox-body">
                <div class="row">
                    <div class="col-md-2">
                        <img src="{{$supplier['image']}}" class="img-fluid" alt="supplier">
                    </div>
                    <div class="col-md-10">
                        <div class="row">
                            <div class="col-md-6 row mb-3">
                                <div class="col-5 font-weight-bold">Supplier Name:</div>
                                <div class="col-md-7">{{$supplier['name']}}</div>
                            </div>
                            <div class="col-md-6 row mb-3">
                                <div class="col-5 font-weight-bold">Supplier Email:</div>
                                <div class="col-md-7">{{$supplier['email']}}</div>
                            </div>
                            <div class="col-md-6 row mb-3">
                                <div class="col-5 font-weight-bold">Supplier Phone:</div>
                                <div class="col-md-7">{{$supplier['phone']}}</div>
                            </div>
                            <div class="col-md-6 row mb-3">
                                <div class="col-5 font-weight-bold">Supplier Address:</div>
                                <div class="col-md-7">{{$supplier['address']}}</div>
                            </div>
                            <div class="col-md-6 row mb-3">
                                <div class="col-5 font-weight-bold">Created By:</div>
                                <div class="col-md-7">{{$supplier['created_by']}}</div>
                            </div>
                            <div class="col-md-6 row mb-3">
                                <div class="col-5 font-weight-bold">Updated By:</div>
                                <div class="col-md-7">{{$supplier['updated_by']}}</div>
                            </div>
                            <div class="col-md-6 row mb-3">
                                <div class="col-5 font-weight-bold">Created At:</div>
                                <div class="col-md-7">{{$supplier['created_at']}}</div>
                            </div>
                            <div class="col-md-6 row mb-3">
                                <div class="col-5 font-weight-bold">Updated At:</div>
                                <div class="col-md-7">{{$supplier['updated_at']}}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection